/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    'CardOrder.component': typeof import('./src/components/CardOrder.component.vue')['default']
    PrimeButton: typeof import('primevue/button')['default']
    PrimeColumn: typeof import('primevue/column')['default']
    PrimeDataTable: typeof import('primevue/datatable')['default']
    PrimeDialog: typeof import('primevue/dialog')['default']
    PrimeIconField: typeof import('primevue/iconfield')['default']
    PrimeInputIcon: typeof import('primevue/inputicon')['default']
    PrimeInputText: typeof import('primevue/inputtext')['default']
    PrimeTag: typeof import('primevue/tag')['default']
    PrimeToolbar: typeof import('primevue/toolbar')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
