/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    'ConfirmModalWrapper.component': typeof import('./src/components/ui/confirm-modal-wrapper.component.vue')['default']
    'CrudDataTable.component': typeof import('./src/components/ui/crud-data-table.component.vue')['default']
    DataTable: typeof import('./src/components/ui/data-table.vue')['default']
    'DataTable.component': typeof import('./src/components/ui/data-table.component.vue')['default']
    InputText: typeof import('./src/components/ui/form/input-text.vue')['default']
    'InputText.component': typeof import('./src/components/ui/form/input-text.component.vue')['default']
    ModalWrapper: typeof import('./src/components/ui/modal-wrapper.vue')['default']
    'ModalWrapper.component': typeof import('./src/components/ui/modal-wrapper.component.vue')['default']
    PrimeButton: typeof import('primevue/button')['default']
    PrimeColumn: typeof import('primevue/column')['default']
    PrimeConfirmDialog: typeof import('primevue/confirmdialog')['default']
    PrimeDataTable: typeof import('primevue/datatable')['default']
    PrimeDialog: typeof import('primevue/dialog')['default']
    PrimeDropdown: typeof import('primevue/dropdown')['default']
    PrimeFloatLabel: typeof import('primevue/floatlabel')['default']
    PrimeIconField: typeof import('primevue/iconfield')['default']
    PrimeImage: typeof import('primevue/image')['default']
    PrimeInputIcon: typeof import('primevue/inputicon')['default']
    PrimeInputText: typeof import('primevue/inputtext')['default']
    PrimeMultiSelect: typeof import('primevue/multiselect')['default']
    PrimeToast: typeof import('primevue/toast')['default']
    PrimeToolbar: typeof import('primevue/toolbar')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
