/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    'card.component': typeof import('./components/ui/card.component.vue')['default']
    PrimeAccordion: typeof import('primevue/accordion')['default']
    PrimeAccordionTab: typeof import('primevue/accordiontab')['default']
    PrimeBadge: typeof import('primevue/badge')['default']
    PrimeButton: typeof import('primevue/button')['default']
    PrimeCard: typeof import('primevue/card')['default']
    PrimeConfirmDialog: typeof import('primevue/confirmdialog')['default']
    PrimeDataView: typeof import('primevue/dataview')['default']
    PrimeDialog: typeof import('primevue/dialog')['default']
    PrimeDrawer: typeof import('primevue/drawer')['default']
    PrimeIconField: typeof import('primevue/iconfield')['default']
    PrimeImage: typeof import('primevue/image')['default']
    PrimeOverlayBadge: typeof import('primevue/overlaybadge')['default']
    PrimeRadioButton: typeof import('primevue/radiobutton')['default']
    PrimeSplitter: typeof import('primevue/splitter')['default']
    PrimeSplitterPanel: typeof import('primevue/splitterpanel')['default']
    PrimeStep: typeof import('primevue/step')['default']
    PrimeStepList: typeof import('primevue/steplist')['default']
    PrimeStepPanel: typeof import('primevue/steppanel')['default']
    PrimeStepPanels: typeof import('primevue/steppanels')['default']
    PrimeStepper: typeof import('primevue/stepper')['default']
    PrimeTag: typeof import('primevue/tag')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    splitter: typeof import('./components/ui/splitter.component.vue')['default']
    'stepper.component': typeof import('./components/ui/stepper/stepper.component.vue')['default']
  }
}
