/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    'card.component': typeof import('./components/ui/card.component.vue')['default']
    PrimeButton: typeof import('primevue/button')['default']
    PrimeCard: typeof import('primevue/card')['default']
    PrimeColumn: typeof import('primevue/column')['default']
    PrimeDataTable: typeof import('primevue/datatable')['default']
    PrimeDialog: typeof import('primevue/dialog')['default']
    PrimeDropdown: typeof import('primevue/dropdown')['default']
    PrimeFloatLabel: typeof import('primevue/floatlabel')['default']
    PrimeIconField: typeof import('primevue/iconfield')['default']
    PrimeImage: typeof import('primevue/image')['default']
    PrimeInputIcon: typeof import('primevue/inputicon')['default']
    PrimeInputNumber: typeof import('primevue/inputnumber')['default']
    PrimeInputText: typeof import('primevue/inputtext')['default']
    PrimeMultiSelect: typeof import('primevue/multiselect')['default']
    PrimeRadioButton: typeof import('primevue/radiobutton')['default']
    PrimeStep: typeof import('primevue/step')['default']
    PrimeStepList: typeof import('primevue/steplist')['default']
    PrimeStepPanel: typeof import('primevue/steppanel')['default']
    PrimeStepPanels: typeof import('primevue/steppanels')['default']
    PrimeStepper: typeof import('primevue/stepper')['default']
    PrimeTabMenu: typeof import('primevue/tabmenu')['default']
    PrimeTag: typeof import('primevue/tag')['default']
    PrimeToast: typeof import('primevue/toast')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    'stepper.component': typeof import('./components/ui/stepper.component.vue')['default']
  }
}
