name: PR

on:
  pull_request:
    branches:
      - main
      - next

run-name: 'PR - ${{ github.event.pull_request.title }}'

jobs:
  build:
    uses: stygma-projects/.github/.github/workflows/build.yml@main
    with:
      is_build: true
      is_type_checked: true
      is_tested: false
